# Generated by Django 4.2.6 on 2023-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_showtime_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phno',
            field=models.BigIntegerField(),
        ),
    ]
