# Generated by Django 4.2.8 on 2024-01-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookPublication',
            new_name='BookPublishedon',
        ),
    ]
