# Generated by Django 4.2.8 on 2024-01-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_rename_bookpublication_book_bookpublishedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookPublishedon',
            new_name='BookPublishedOn',
        ),
    ]
