# Generated by Django 4.2.8 on 2024-01-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_rename_bookpublishedon_book_bookpublishedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='AuthorEmail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='AuthorGender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookDescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookPublishedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
